apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    app: techtrends
    tag: latest
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: techtrends
    tag: latest
  ports:
    - port: 4111
      targetPort: 4111
      protocol: TCP
